// Import the createSlice function from the Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

// Create a slice of the Redux store for managing UI state
const uiSlice = createSlice({
  // Name of the slice, used in the Redux store state
  name: "ui",

  // Initial state for the UI slice
  initialState: { notification: null },

  // Reducer functions to handle actions and update the state
  reducers: {
    // Reducer function to handle the showNotification action
    showNotification(state, action) {
      // Update the state with the notification data from the action payload
      state.notification = {
        status: action.payload.status,
        title: action.payload.title,
        message: action.payload.message,
      };
    },
  },
});

// Export the action creators generated by createSlice
export const uiActions = uiSlice.actions;

// Export the entire uiSlice, including the reducer and action creators
export default uiSlice;
